/**
 * @generated
 */
module.exports = {
  "ability/network": {
    "id": "ability/network",
    "title": "网络",
    "sidebar_label": "网络",
    "source": "ability/network.md",
    "permalink": "ability/network.html",
    "localized_id": "ability/network",
    "language": "en",
    "sidebar": "guide",
    "category": "基础能力",
    "subcategory": null,
    "order": 11,
    "next_id": "ability/storage",
    "next": "ability/storage",
    "previous_id": "framework/vue",
    "previous": "framework/vue",
    "previous_title": "使用Vue的限制",
    "next_title": "存储"
  },
  "ability/storage": {
    "id": "ability/storage",
    "title": "存储",
    "sidebar_label": "存储",
    "source": "ability/storage.md",
    "permalink": "ability/storage.html",
    "localized_id": "ability/storage",
    "language": "en",
    "sidebar": "guide",
    "category": "基础能力",
    "subcategory": null,
    "order": 12,
    "next_id": "open/login",
    "next": "open/login",
    "previous_id": "ability/network",
    "previous": "ability/network",
    "previous_title": "网络",
    "next_title": "小程序登录"
  },
  "api/device/canIUse": {
    "id": "api/device/canIUse",
    "title": "bl.canIUse",
    "sidebar_label": "bl.canIUse",
    "source": "api/device/canIUse.md",
    "permalink": "api/device/canIUse.html",
    "localized_id": "api/device/canIUse",
    "language": "en"
  },
  "api/device/getBatteryInfo": {
    "id": "api/device/getBatteryInfo",
    "title": "bl.getBatteryInfo",
    "sidebar_label": "bl.getBatteryInfo",
    "source": "api/device/getBatteryInfo.md",
    "permalink": "api/device/getBatteryInfo.html",
    "localized_id": "api/device/getBatteryInfo",
    "language": "en"
  },
  "api/device/getBatteryInfoSync": {
    "id": "api/device/getBatteryInfoSync",
    "title": "bl.getBatteryInfoSync",
    "sidebar_label": "bl.getBatteryInfoSync",
    "source": "api/device/getBatteryInfoSync.md",
    "permalink": "api/device/getBatteryInfoSync.html",
    "localized_id": "api/device/getBatteryInfoSync",
    "language": "en"
  },
  "api/device/getClipboardData": {
    "id": "api/device/getClipboardData",
    "title": "bl.getClipboardData",
    "sidebar_label": "bl.getClipboardData",
    "source": "api/device/getClipboardData.md",
    "permalink": "api/device/getClipboardData.html",
    "localized_id": "api/device/getClipboardData",
    "language": "en"
  },
  "api/device/getNetworkType": {
    "id": "api/device/getNetworkType",
    "title": "bl.getNetworkType",
    "sidebar_label": "bl.getNetworkType",
    "source": "api/device/getNetworkType.md",
    "permalink": "api/device/getNetworkType.html",
    "localized_id": "api/device/getNetworkType",
    "language": "en"
  },
  "api/device/getScreenBrightness": {
    "id": "api/device/getScreenBrightness",
    "title": "bl.getScreenBrightness",
    "sidebar_label": "bl.getScreenBrightness",
    "source": "api/device/getScreenBrightness.md",
    "permalink": "api/device/getScreenBrightness.html",
    "localized_id": "api/device/getScreenBrightness",
    "language": "en"
  },
  "api/device/getSystemInfo": {
    "id": "api/device/getSystemInfo",
    "title": "bl.getSystemInfo",
    "sidebar_label": "bl.getSystemInfo",
    "source": "api/device/getSystemInfo.md",
    "permalink": "api/device/getSystemInfo.html",
    "localized_id": "api/device/getSystemInfo",
    "language": "en"
  },
  "api/device/getSystemInfoSync": {
    "id": "api/device/getSystemInfoSync",
    "title": "bl.getSystemInfoSync",
    "sidebar_label": "bl.getSystemInfoSync",
    "source": "api/device/getSystemInfoSync.md",
    "permalink": "api/device/getSystemInfoSync.html",
    "localized_id": "api/device/getSystemInfoSync",
    "language": "en"
  },
  "api/device/makePhoneCall": {
    "id": "api/device/makePhoneCall",
    "title": "bl.makePhoneCall",
    "sidebar_label": "bl.makePhoneCall",
    "source": "api/device/makePhoneCall.md",
    "permalink": "api/device/makePhoneCall.html",
    "localized_id": "api/device/makePhoneCall",
    "language": "en"
  },
  "api/device/onAccelerometerChange": {
    "id": "api/device/onAccelerometerChange",
    "title": "bl.onAccelerometerChange",
    "sidebar_label": "bl.onAccelerometerChange",
    "source": "api/device/onAccelerometerChange.md",
    "permalink": "api/device/onAccelerometerChange.html",
    "localized_id": "api/device/onAccelerometerChange",
    "language": "en"
  },
  "api/device/onCompassChange": {
    "id": "api/device/onCompassChange",
    "title": "bl.onCompassChange",
    "sidebar_label": "bl.onCompassChange",
    "source": "api/device/onCompassChange.md",
    "permalink": "api/device/onCompassChange.html",
    "localized_id": "api/device/onCompassChange",
    "language": "en"
  },
  "api/device/onDeviceMotionChange": {
    "id": "api/device/onDeviceMotionChange",
    "title": "bl.onDeviceMotionChange",
    "sidebar_label": "bl.onDeviceMotionChange",
    "source": "api/device/onDeviceMotionChange.md",
    "permalink": "api/device/onDeviceMotionChange.html",
    "localized_id": "api/device/onDeviceMotionChange",
    "language": "en"
  },
  "api/device/onGyroscopeChange": {
    "id": "api/device/onGyroscopeChange",
    "title": "bl.onGyroscopeChange",
    "sidebar_label": "bl.onGyroscopeChange",
    "source": "api/device/onGyroscopeChange.md",
    "permalink": "api/device/onGyroscopeChange.html",
    "localized_id": "api/device/onGyroscopeChange",
    "language": "en"
  },
  "api/device/onMemoryWarning": {
    "id": "api/device/onMemoryWarning",
    "title": "bl.onMemoryWarning",
    "sidebar_label": "bl.onMemoryWarning",
    "source": "api/device/onMemoryWarning.md",
    "permalink": "api/device/onMemoryWarning.html",
    "localized_id": "api/device/onMemoryWarning",
    "language": "en"
  },
  "api/device/onNetworkStatusChange": {
    "id": "api/device/onNetworkStatusChange",
    "title": "bl.onNetworkStatusChange",
    "sidebar_label": "bl.onNetworkStatusChange",
    "source": "api/device/onNetworkStatusChange.md",
    "permalink": "api/device/onNetworkStatusChange.html",
    "localized_id": "api/device/onNetworkStatusChange",
    "language": "en"
  },
  "api/device/onUserCaptureScreen": {
    "id": "api/device/onUserCaptureScreen",
    "title": "bl.onUserCaptureScreen",
    "sidebar_label": "bl.onUserCaptureScreen",
    "source": "api/device/onUserCaptureScreen.md",
    "permalink": "api/device/onUserCaptureScreen.html",
    "localized_id": "api/device/onUserCaptureScreen",
    "language": "en"
  },
  "api/device/scanCode": {
    "id": "api/device/scanCode",
    "title": "bl.scanCode",
    "sidebar_label": "bl.scanCode",
    "source": "api/device/scanCode.md",
    "permalink": "api/device/scanCode.html",
    "localized_id": "api/device/scanCode",
    "language": "en"
  },
  "api/device/setClipboardData": {
    "id": "api/device/setClipboardData",
    "title": "bl.setClipboardData",
    "sidebar_label": "bl.setClipboardData",
    "source": "api/device/setClipboardData.md",
    "permalink": "api/device/setClipboardData.html",
    "localized_id": "api/device/setClipboardData",
    "language": "en"
  },
  "api/device/setKeepScreenOn": {
    "id": "api/device/setKeepScreenOn",
    "title": "bl.setKeepScreenOn",
    "sidebar_label": "bl.setKeepScreenOn",
    "source": "api/device/setKeepScreenOn.md",
    "permalink": "api/device/setKeepScreenOn.html",
    "localized_id": "api/device/setKeepScreenOn",
    "language": "en"
  },
  "api/device/setScreenBrightness": {
    "id": "api/device/setScreenBrightness",
    "title": "bl.setScreenBrightness",
    "sidebar_label": "bl.setScreenBrightness",
    "source": "api/device/setScreenBrightness.md",
    "permalink": "api/device/setScreenBrightness.html",
    "localized_id": "api/device/setScreenBrightness",
    "language": "en"
  },
  "api/device/startAccelerometer": {
    "id": "api/device/startAccelerometer",
    "title": "bl.startAccelerometer",
    "sidebar_label": "bl.startAccelerometer",
    "source": "api/device/startAccelerometer.md",
    "permalink": "api/device/startAccelerometer.html",
    "localized_id": "api/device/startAccelerometer",
    "language": "en"
  },
  "api/device/startCompass": {
    "id": "api/device/startCompass",
    "title": "bl.startCompass",
    "sidebar_label": "bl.startCompass",
    "source": "api/device/startCompass.md",
    "permalink": "api/device/startCompass.html",
    "localized_id": "api/device/startCompass",
    "language": "en"
  },
  "api/device/startDeviceMotionListening": {
    "id": "api/device/startDeviceMotionListening",
    "title": "bl.startDeviceMotionListening",
    "sidebar_label": "bl.startDeviceMotionListening",
    "source": "api/device/startDeviceMotionListening.md",
    "permalink": "api/device/startDeviceMotionListening.html",
    "localized_id": "api/device/startDeviceMotionListening",
    "language": "en"
  },
  "api/device/startGyroscope": {
    "id": "api/device/startGyroscope",
    "title": "bl.startGyroscope",
    "sidebar_label": "bl.startGyroscope",
    "source": "api/device/startGyroscope.md",
    "permalink": "api/device/startGyroscope.html",
    "localized_id": "api/device/startGyroscope",
    "language": "en"
  },
  "api/device/stopAccelerometer": {
    "id": "api/device/stopAccelerometer",
    "title": "bl.stopAccelerometer",
    "sidebar_label": "bl.stopAccelerometer",
    "source": "api/device/stopAccelerometer.md",
    "permalink": "api/device/stopAccelerometer.html",
    "localized_id": "api/device/stopAccelerometer",
    "language": "en"
  },
  "api/device/stopCompass": {
    "id": "api/device/stopCompass",
    "title": "bl.stopCompass",
    "sidebar_label": "bl.stopCompass",
    "source": "api/device/stopCompass.md",
    "permalink": "api/device/stopCompass.html",
    "localized_id": "api/device/stopCompass",
    "language": "en"
  },
  "api/device/stopDeviceMotionListening": {
    "id": "api/device/stopDeviceMotionListening",
    "title": "bl.stopDeviceMotionListening",
    "sidebar_label": "bl.stopDeviceMotionListening",
    "source": "api/device/stopDeviceMotionListening.md",
    "permalink": "api/device/stopDeviceMotionListening.html",
    "localized_id": "api/device/stopDeviceMotionListening",
    "language": "en"
  },
  "api/device/stopGyroscope": {
    "id": "api/device/stopGyroscope",
    "title": "bl.stopGyroscope",
    "sidebar_label": "bl.stopGyroscope",
    "source": "api/device/stopGyroscope.md",
    "permalink": "api/device/stopGyroscope.html",
    "localized_id": "api/device/stopGyroscope",
    "language": "en"
  },
  "api/device/vibrateLong": {
    "id": "api/device/vibrateLong",
    "title": "bl.vibrateLong",
    "sidebar_label": "bl.vibrateLong",
    "source": "api/device/vibrateLong.md",
    "permalink": "api/device/vibrateLong.html",
    "localized_id": "api/device/vibrateLong",
    "language": "en"
  },
  "api/device/vibrateShort": {
    "id": "api/device/vibrateShort",
    "title": "bl.vibrateShort",
    "sidebar_label": "bl.vibrateShort",
    "source": "api/device/vibrateShort.md",
    "permalink": "api/device/vibrateShort.html",
    "localized_id": "api/device/vibrateShort",
    "language": "en"
  },
  "api/dom/createIntersectionObserver": {
    "id": "api/dom/createIntersectionObserver",
    "title": "bl.createIntersectionObserver",
    "sidebar_label": "bl.createIntersectionObserver",
    "source": "api/dom/createIntersectionObserver.md",
    "permalink": "api/dom/createIntersectionObserver.html",
    "localized_id": "api/dom/createIntersectionObserver",
    "language": "en"
  },
  "api/dom/createSelectorQuery": {
    "id": "api/dom/createSelectorQuery",
    "title": "bl.createSelectorQuery",
    "sidebar_label": "bl.createSelectorQuery",
    "source": "api/dom/createSelectorQuery.md",
    "permalink": "api/dom/createSelectorQuery.html",
    "localized_id": "api/dom/createSelectorQuery",
    "language": "en"
  },
  "api/dom/IntersectionObserver.disconnect": {
    "id": "api/dom/IntersectionObserver.disconnect",
    "title": "IntersectionObserver.disconnect",
    "sidebar_label": "IntersectionObserver.disconnect",
    "source": "api/dom/IntersectionObserver.disconnect.md",
    "permalink": "api/dom/IntersectionObserver.disconnect.html",
    "localized_id": "api/dom/IntersectionObserver.disconnect",
    "language": "en"
  },
  "api/dom/IntersectionObserver": {
    "id": "api/dom/IntersectionObserver",
    "title": "IntersectionObserver",
    "sidebar_label": "IntersectionObserver",
    "source": "api/dom/IntersectionObserver.md",
    "permalink": "api/dom/IntersectionObserver.html",
    "localized_id": "api/dom/IntersectionObserver",
    "language": "en"
  },
  "api/dom/IntersectionObserver.observe": {
    "id": "api/dom/IntersectionObserver.observe",
    "title": "IntersectionObserver.observe",
    "sidebar_label": "IntersectionObserver.observe",
    "source": "api/dom/IntersectionObserver.observe.md",
    "permalink": "api/dom/IntersectionObserver.observe.html",
    "localized_id": "api/dom/IntersectionObserver.observe",
    "language": "en"
  },
  "api/dom/IntersectionObserver.relativeTo": {
    "id": "api/dom/IntersectionObserver.relativeTo",
    "title": "IntersectionObserver.relativeTo",
    "sidebar_label": "IntersectionObserver.relativeTo",
    "source": "api/dom/IntersectionObserver.relativeTo.md",
    "permalink": "api/dom/IntersectionObserver.relativeTo.html",
    "localized_id": "api/dom/IntersectionObserver.relativeTo",
    "language": "en"
  },
  "api/dom/IntersectionObserver.relativeToViewport": {
    "id": "api/dom/IntersectionObserver.relativeToViewport",
    "title": "IntersectionObserver.relativeToViewport",
    "sidebar_label": "IntersectionObserver.relativeToViewport",
    "source": "api/dom/IntersectionObserver.relativeToViewport.md",
    "permalink": "api/dom/IntersectionObserver.relativeToViewport.html",
    "localized_id": "api/dom/IntersectionObserver.relativeToViewport",
    "language": "en"
  },
  "api/dom/NodesRef.boundingClientRect": {
    "id": "api/dom/NodesRef.boundingClientRect",
    "title": "NodesRef.boundingClientRect",
    "sidebar_label": "NodesRef.boundingClientRect",
    "source": "api/dom/NodesRef.boundingClientRect.md",
    "permalink": "api/dom/NodesRef.boundingClientRect.html",
    "localized_id": "api/dom/NodesRef.boundingClientRect",
    "language": "en"
  },
  "api/dom/NodesRef.fields": {
    "id": "api/dom/NodesRef.fields",
    "title": "NodesRef.fields",
    "sidebar_label": "NodesRef.fields",
    "source": "api/dom/NodesRef.fields.md",
    "permalink": "api/dom/NodesRef.fields.html",
    "localized_id": "api/dom/NodesRef.fields",
    "language": "en"
  },
  "api/dom/NodesRef": {
    "id": "api/dom/NodesRef",
    "title": "NodesRef",
    "sidebar_label": "NodesRef",
    "source": "api/dom/NodesRef.md",
    "permalink": "api/dom/NodesRef.html",
    "localized_id": "api/dom/NodesRef",
    "language": "en"
  },
  "api/dom/NodesRef.scrollOffset": {
    "id": "api/dom/NodesRef.scrollOffset",
    "title": "NodesRef.scrollOffset",
    "sidebar_label": "NodesRef.scrollOffset",
    "source": "api/dom/NodesRef.scrollOffset.md",
    "permalink": "api/dom/NodesRef.scrollOffset.html",
    "localized_id": "api/dom/NodesRef.scrollOffset",
    "language": "en"
  },
  "api/dom/SelectorQuery.exec": {
    "id": "api/dom/SelectorQuery.exec",
    "title": "SelectorQuery.exec",
    "sidebar_label": "SelectorQuery.exec",
    "source": "api/dom/SelectorQuery.exec.md",
    "permalink": "api/dom/SelectorQuery.exec.html",
    "localized_id": "api/dom/SelectorQuery.exec",
    "language": "en"
  },
  "api/dom/SelectorQuery.in": {
    "id": "api/dom/SelectorQuery.in",
    "title": "SelectorQuery.in",
    "sidebar_label": "SelectorQuery.in",
    "source": "api/dom/SelectorQuery.in.md",
    "permalink": "api/dom/SelectorQuery.in.html",
    "localized_id": "api/dom/SelectorQuery.in",
    "language": "en"
  },
  "api/dom/SelectorQuery": {
    "id": "api/dom/SelectorQuery",
    "title": "SelectorQuery",
    "sidebar_label": "SelectorQuery",
    "source": "api/dom/SelectorQuery.md",
    "permalink": "api/dom/SelectorQuery.html",
    "localized_id": "api/dom/SelectorQuery",
    "language": "en"
  },
  "api/dom/SelectorQuery.select": {
    "id": "api/dom/SelectorQuery.select",
    "title": "SelectorQuery.select",
    "sidebar_label": "SelectorQuery.select",
    "source": "api/dom/SelectorQuery.select.md",
    "permalink": "api/dom/SelectorQuery.select.html",
    "localized_id": "api/dom/SelectorQuery.select",
    "language": "en"
  },
  "api/dom/SelectorQuery.selectAll": {
    "id": "api/dom/SelectorQuery.selectAll",
    "title": "SelectorQuery.selectAll",
    "sidebar_label": "SelectorQuery.selectAll",
    "source": "api/dom/SelectorQuery.selectAll.md",
    "permalink": "api/dom/SelectorQuery.selectAll.html",
    "localized_id": "api/dom/SelectorQuery.selectAll",
    "language": "en"
  },
  "api/dom/SelectorQuery.selectViewport": {
    "id": "api/dom/SelectorQuery.selectViewport",
    "title": "SelectorQuery.selectViewport",
    "sidebar_label": "SelectorQuery.selectViewport",
    "source": "api/dom/SelectorQuery.selectViewport.md",
    "permalink": "api/dom/SelectorQuery.selectViewport.html",
    "localized_id": "api/dom/SelectorQuery.selectViewport",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.access": {
    "id": "api/file/FileSystemManager/FileSystemManager.access",
    "title": "FileSystemManager.access",
    "sidebar_label": "FileSystemManager.access",
    "source": "api/file/FileSystemManager/FileSystemManager.access.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.access.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.access",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.accessSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.accessSync",
    "title": "FileSystemManager.accessSync",
    "sidebar_label": "FileSystemManager.accessSync",
    "source": "api/file/FileSystemManager/FileSystemManager.accessSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.accessSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.accessSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.appendFile": {
    "id": "api/file/FileSystemManager/FileSystemManager.appendFile",
    "title": "FileSystemManager.appendFile",
    "sidebar_label": "FileSystemManager.appendFile",
    "source": "api/file/FileSystemManager/FileSystemManager.appendFile.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.appendFile.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.appendFile",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.appendFileSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.appendFileSync",
    "title": "FileSystemManager.appendFileSync",
    "sidebar_label": "FileSystemManager.appendFileSync",
    "source": "api/file/FileSystemManager/FileSystemManager.appendFileSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.appendFileSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.appendFileSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.copyFile": {
    "id": "api/file/FileSystemManager/FileSystemManager.copyFile",
    "title": "FileSystemManager.copyFile",
    "sidebar_label": "FileSystemManager.copyFile",
    "source": "api/file/FileSystemManager/FileSystemManager.copyFile.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.copyFile.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.copyFile",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.copyFileSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.copyFileSync",
    "title": "FileSystemManager.copyFileSync",
    "sidebar_label": "FileSystemManager.copyFileSync",
    "source": "api/file/FileSystemManager/FileSystemManager.copyFileSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.copyFileSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.copyFileSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.getFileInfo": {
    "id": "api/file/FileSystemManager/FileSystemManager.getFileInfo",
    "title": "FileSystemManager.getFileInfo",
    "sidebar_label": "FileSystemManager.getFileInfo",
    "source": "api/file/FileSystemManager/FileSystemManager.getFileInfo.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.getFileInfo.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.getFileInfo",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.getSavedFileList": {
    "id": "api/file/FileSystemManager/FileSystemManager.getSavedFileList",
    "title": "FileSystemManager.getSavedFileList",
    "sidebar_label": "FileSystemManager.getSavedFileList",
    "source": "api/file/FileSystemManager/FileSystemManager.getSavedFileList.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.getSavedFileList.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.getSavedFileList",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.mkdir": {
    "id": "api/file/FileSystemManager/FileSystemManager.mkdir",
    "title": "FileSystemManager.mkdir",
    "sidebar_label": "FileSystemManager.mkdir",
    "source": "api/file/FileSystemManager/FileSystemManager.mkdir.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.mkdir.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.mkdir",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.mkdirSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.mkdirSync",
    "title": "FileSystemManager.mkdirSync",
    "sidebar_label": "FileSystemManager.mkdirSync",
    "source": "api/file/FileSystemManager/FileSystemManager.mkdirSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.mkdirSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.mkdirSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.readdir": {
    "id": "api/file/FileSystemManager/FileSystemManager.readdir",
    "title": "FileSystemManager.readdir",
    "sidebar_label": "FileSystemManager.readdir",
    "source": "api/file/FileSystemManager/FileSystemManager.readdir.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.readdir.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.readdir",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.readdirSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.readdirSync",
    "title": "FileSystemManager.readdirSync",
    "sidebar_label": "FileSystemManager.readdirSync",
    "source": "api/file/FileSystemManager/FileSystemManager.readdirSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.readdirSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.readdirSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.readFile": {
    "id": "api/file/FileSystemManager/FileSystemManager.readFile",
    "title": "FileSystemManager.readFile",
    "sidebar_label": "FileSystemManager.readFile",
    "source": "api/file/FileSystemManager/FileSystemManager.readFile.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.readFile.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.readFile",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.readFileSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.readFileSync",
    "title": "FileSystemManager.readFileSync",
    "sidebar_label": "FileSystemManager.readFileSync",
    "source": "api/file/FileSystemManager/FileSystemManager.readFileSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.readFileSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.readFileSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.removeSavedFile": {
    "id": "api/file/FileSystemManager/FileSystemManager.removeSavedFile",
    "title": "FileSystemManager.removeSavedFile",
    "sidebar_label": "FileSystemManager.removeSavedFile",
    "source": "api/file/FileSystemManager/FileSystemManager.removeSavedFile.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.removeSavedFile.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.removeSavedFile",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.rename": {
    "id": "api/file/FileSystemManager/FileSystemManager.rename",
    "title": "FileSystemManager.rename",
    "sidebar_label": "FileSystemManager.rename",
    "source": "api/file/FileSystemManager/FileSystemManager.rename.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.rename.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.rename",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.renameSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.renameSync",
    "title": "FileSystemManager.renameSync",
    "sidebar_label": "FileSystemManager.renameSync",
    "source": "api/file/FileSystemManager/FileSystemManager.renameSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.renameSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.renameSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.rmdir": {
    "id": "api/file/FileSystemManager/FileSystemManager.rmdir",
    "title": "FileSystemManager.rmdir",
    "sidebar_label": "FileSystemManager.rmdir",
    "source": "api/file/FileSystemManager/FileSystemManager.rmdir.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.rmdir.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.rmdir",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.rmdirSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.rmdirSync",
    "title": "FileSystemManager.rmdirSync",
    "sidebar_label": "FileSystemManager.rmdirSync",
    "source": "api/file/FileSystemManager/FileSystemManager.rmdirSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.rmdirSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.rmdirSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.saveFile": {
    "id": "api/file/FileSystemManager/FileSystemManager.saveFile",
    "title": "FileSystemManager.saveFile",
    "sidebar_label": "FileSystemManager.saveFile",
    "source": "api/file/FileSystemManager/FileSystemManager.saveFile.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.saveFile.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.saveFile",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.saveFileSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.saveFileSync",
    "title": "FileSystemManager.saveFileSync",
    "sidebar_label": "FileSystemManager.saveFileSync",
    "source": "api/file/FileSystemManager/FileSystemManager.saveFileSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.saveFileSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.saveFileSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.stat": {
    "id": "api/file/FileSystemManager/FileSystemManager.stat",
    "title": "FileSystemManager.stat",
    "sidebar_label": "FileSystemManager.stat",
    "source": "api/file/FileSystemManager/FileSystemManager.stat.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.stat.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.stat",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.statSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.statSync",
    "title": "FileSystemManager.statSync",
    "sidebar_label": "FileSystemManager.statSync",
    "source": "api/file/FileSystemManager/FileSystemManager.statSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.statSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.statSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.unlink": {
    "id": "api/file/FileSystemManager/FileSystemManager.unlink",
    "title": "FileSystemManager.unlink",
    "sidebar_label": "FileSystemManager.unlink",
    "source": "api/file/FileSystemManager/FileSystemManager.unlink.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.unlink.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.unlink",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.unlinkSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.unlinkSync",
    "title": "FileSystemManager.unlinkSync",
    "sidebar_label": "FileSystemManager.unlinkSync",
    "source": "api/file/FileSystemManager/FileSystemManager.unlinkSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.unlinkSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.unlinkSync",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.unzip": {
    "id": "api/file/FileSystemManager/FileSystemManager.unzip",
    "title": "FileSystemManager.unzip",
    "sidebar_label": "FileSystemManager.unzip",
    "source": "api/file/FileSystemManager/FileSystemManager.unzip.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.unzip.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.unzip",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.writeFile": {
    "id": "api/file/FileSystemManager/FileSystemManager.writeFile",
    "title": "FileSystemManager.writeFile",
    "sidebar_label": "FileSystemManager.writeFile",
    "source": "api/file/FileSystemManager/FileSystemManager.writeFile.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.writeFile.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.writeFile",
    "language": "en"
  },
  "api/file/FileSystemManager/FileSystemManager.writeFileSync": {
    "id": "api/file/FileSystemManager/FileSystemManager.writeFileSync",
    "title": "FileSystemManager.writeFileSync",
    "sidebar_label": "FileSystemManager.writeFileSync",
    "source": "api/file/FileSystemManager/FileSystemManager.writeFileSync.md",
    "permalink": "api/file/FileSystemManager/FileSystemManager.writeFileSync.html",
    "localized_id": "api/file/FileSystemManager/FileSystemManager.writeFileSync",
    "language": "en"
  },
  "api/file/getFileInfo": {
    "id": "api/file/getFileInfo",
    "title": "bl.getFileInfo",
    "sidebar_label": "bl.getFileInfo",
    "source": "api/file/getFileInfo.md",
    "permalink": "api/file/getFileInfo.html",
    "localized_id": "api/file/getFileInfo",
    "language": "en"
  },
  "api/file/getSavedFileInfo": {
    "id": "api/file/getSavedFileInfo",
    "title": "bl.getSavedFileInfo",
    "sidebar_label": "bl.getSavedFileInfo",
    "source": "api/file/getSavedFileInfo.md",
    "permalink": "api/file/getSavedFileInfo.html",
    "localized_id": "api/file/getSavedFileInfo",
    "language": "en"
  },
  "api/file/getSavedFileList": {
    "id": "api/file/getSavedFileList",
    "title": "bl.getSavedFileList",
    "sidebar_label": "bl.getSavedFileList",
    "source": "api/file/getSavedFileList.md",
    "permalink": "api/file/getSavedFileList.html",
    "localized_id": "api/file/getSavedFileList",
    "language": "en"
  },
  "api/file/removeSavedFile": {
    "id": "api/file/removeSavedFile",
    "title": "bl.removeSavedFile",
    "sidebar_label": "bl.removeSavedFile",
    "source": "api/file/removeSavedFile.md",
    "permalink": "api/file/removeSavedFile.html",
    "localized_id": "api/file/removeSavedFile",
    "language": "en"
  },
  "api/file/saveFile": {
    "id": "api/file/saveFile",
    "title": "bl.saveFile",
    "sidebar_label": "bl.saveFile",
    "source": "api/file/saveFile.md",
    "permalink": "api/file/saveFile.html",
    "localized_id": "api/file/saveFile",
    "language": "en"
  },
  "api/life/getLaunchOptions": {
    "id": "api/life/getLaunchOptions",
    "title": "bl.getLaunchOptions",
    "sidebar_label": "bl.getLaunchOptions",
    "source": "api/life/getLaunchOptions.md",
    "permalink": "api/life/getLaunchOptions.html",
    "localized_id": "api/life/getLaunchOptions",
    "language": "en"
  },
  "api/life/getLaunchOptionsSync": {
    "id": "api/life/getLaunchOptionsSync",
    "title": "bl.getLaunchOptionsSync",
    "sidebar_label": "bl.getLaunchOptionsSync",
    "source": "api/life/getLaunchOptionsSync.md",
    "permalink": "api/life/getLaunchOptionsSync.html",
    "localized_id": "api/life/getLaunchOptionsSync",
    "language": "en"
  },
  "api/life/onLanunch": {
    "id": "api/life/onLanunch",
    "title": "onLanunch",
    "sidebar_label": "onLanunch",
    "source": "api/life/onLanunch.md",
    "permalink": "api/life/onLanunch.html",
    "localized_id": "api/life/onLanunch",
    "language": "en"
  },
  "api/life/onShow": {
    "id": "api/life/onShow",
    "title": "onShow",
    "sidebar_label": "onShow",
    "source": "api/life/onShow.md",
    "permalink": "api/life/onShow.html",
    "localized_id": "api/life/onShow",
    "language": "en"
  },
  "api/location/chooseLocation": {
    "id": "api/location/chooseLocation",
    "title": "bl.chooseLocation",
    "sidebar_label": "bl.chooseLocation",
    "source": "api/location/chooseLocation.md",
    "permalink": "api/location/chooseLocation.html",
    "localized_id": "api/location/chooseLocation",
    "language": "en"
  },
  "api/location/getLocation": {
    "id": "api/location/getLocation",
    "title": "bl.getLocation",
    "sidebar_label": "bl.getLocation",
    "source": "api/location/getLocation.md",
    "permalink": "api/location/getLocation.html",
    "localized_id": "api/location/getLocation",
    "language": "en"
  },
  "api/location/openLocation": {
    "id": "api/location/openLocation",
    "title": "bl.openLocation",
    "sidebar_label": "bl.openLocation",
    "source": "api/location/openLocation.md",
    "permalink": "api/location/openLocation.html",
    "localized_id": "api/location/openLocation",
    "language": "en"
  },
  "api/media/chooseImage": {
    "id": "api/media/chooseImage",
    "title": "bl.chooseImage",
    "sidebar_label": "bl.chooseImage",
    "source": "api/media/chooseImage.md",
    "permalink": "api/media/chooseImage.html",
    "localized_id": "api/media/chooseImage",
    "language": "en"
  },
  "api/media/createInnerAudioContext": {
    "id": "api/media/createInnerAudioContext",
    "title": "bl.createInnerAudioContext",
    "sidebar_label": "bl.createInnerAudioContext",
    "source": "api/media/createInnerAudioContext.md",
    "permalink": "api/media/createInnerAudioContext.html",
    "localized_id": "api/media/createInnerAudioContext",
    "language": "en"
  },
  "api/media/getAvailableAudioSources": {
    "id": "api/media/getAvailableAudioSources",
    "title": "bl.getAvailableAudioSources",
    "sidebar_label": "bl.getAvailableAudioSources",
    "source": "api/media/getAvailableAudioSources.md",
    "permalink": "api/media/getAvailableAudioSources.html",
    "localized_id": "api/media/getAvailableAudioSources",
    "language": "en"
  },
  "api/media/getImageInfo": {
    "id": "api/media/getImageInfo",
    "title": "bl.getImageInfo",
    "sidebar_label": "bl.getImageInfo",
    "source": "api/media/getImageInfo.md",
    "permalink": "api/media/getImageInfo.html",
    "localized_id": "api/media/getImageInfo",
    "language": "en"
  },
  "api/media/InnerAudioContext/destroy": {
    "id": "api/media/InnerAudioContext/destroy",
    "title": "InnerAudioContext.destroy",
    "sidebar_label": "InnerAudioContext.destroy",
    "source": "api/media/InnerAudioContext/destroy.md",
    "permalink": "api/media/InnerAudioContext/destroy.html",
    "localized_id": "api/media/InnerAudioContext/destroy",
    "language": "en"
  },
  "api/media/InnerAudioContext/InnerAudioContext": {
    "id": "api/media/InnerAudioContext/InnerAudioContext",
    "title": "InnerAudioContext",
    "sidebar_label": "InnerAudioContext",
    "source": "api/media/InnerAudioContext/InnerAudioContext.md",
    "permalink": "api/media/InnerAudioContext/InnerAudioContext.html",
    "localized_id": "api/media/InnerAudioContext/InnerAudioContext",
    "language": "en"
  },
  "api/media/InnerAudioContext/offCanplay": {
    "id": "api/media/InnerAudioContext/offCanplay",
    "title": "InnerAudioContext.offCanplay",
    "sidebar_label": "InnerAudioContext.offCanplay",
    "source": "api/media/InnerAudioContext/offCanplay.md",
    "permalink": "api/media/InnerAudioContext/offCanplay.html",
    "localized_id": "api/media/InnerAudioContext/offCanplay",
    "language": "en"
  },
  "api/media/InnerAudioContext/offEnded": {
    "id": "api/media/InnerAudioContext/offEnded",
    "title": "InnerAudioContext.offEnded",
    "sidebar_label": "InnerAudioContext.offEnded",
    "source": "api/media/InnerAudioContext/offEnded.md",
    "permalink": "api/media/InnerAudioContext/offEnded.html",
    "localized_id": "api/media/InnerAudioContext/offEnded",
    "language": "en"
  },
  "api/media/InnerAudioContext/offError": {
    "id": "api/media/InnerAudioContext/offError",
    "title": "InnerAudioContext.offError",
    "sidebar_label": "InnerAudioContext.offError",
    "source": "api/media/InnerAudioContext/offError.md",
    "permalink": "api/media/InnerAudioContext/offError.html",
    "localized_id": "api/media/InnerAudioContext/offError",
    "language": "en"
  },
  "api/media/InnerAudioContext/offPause": {
    "id": "api/media/InnerAudioContext/offPause",
    "title": "InnerAudioContext.offPause",
    "sidebar_label": "InnerAudioContext.offPause",
    "source": "api/media/InnerAudioContext/offPause.md",
    "permalink": "api/media/InnerAudioContext/offPause.html",
    "localized_id": "api/media/InnerAudioContext/offPause",
    "language": "en"
  },
  "api/media/InnerAudioContext/offPlay": {
    "id": "api/media/InnerAudioContext/offPlay",
    "title": "InnerAudioContext.offPlay",
    "sidebar_label": "InnerAudioContext.offPlay",
    "source": "api/media/InnerAudioContext/offPlay.md",
    "permalink": "api/media/InnerAudioContext/offPlay.html",
    "localized_id": "api/media/InnerAudioContext/offPlay",
    "language": "en"
  },
  "api/media/InnerAudioContext/offSeeked": {
    "id": "api/media/InnerAudioContext/offSeeked",
    "title": "InnerAudioContext.offSeeked",
    "sidebar_label": "InnerAudioContext.offSeeked",
    "source": "api/media/InnerAudioContext/offSeeked.md",
    "permalink": "api/media/InnerAudioContext/offSeeked.html",
    "localized_id": "api/media/InnerAudioContext/offSeeked",
    "language": "en"
  },
  "api/media/InnerAudioContext/offSeeking": {
    "id": "api/media/InnerAudioContext/offSeeking",
    "title": "InnerAudioContext.offSeeking",
    "sidebar_label": "InnerAudioContext.offSeeking",
    "source": "api/media/InnerAudioContext/offSeeking.md",
    "permalink": "api/media/InnerAudioContext/offSeeking.html",
    "localized_id": "api/media/InnerAudioContext/offSeeking",
    "language": "en"
  },
  "api/media/InnerAudioContext/offStop": {
    "id": "api/media/InnerAudioContext/offStop",
    "title": "InnerAudioContext.offStop",
    "sidebar_label": "InnerAudioContext.offStop",
    "source": "api/media/InnerAudioContext/offStop.md",
    "permalink": "api/media/InnerAudioContext/offStop.html",
    "localized_id": "api/media/InnerAudioContext/offStop",
    "language": "en"
  },
  "api/media/InnerAudioContext/offTimeUpdate": {
    "id": "api/media/InnerAudioContext/offTimeUpdate",
    "title": "InnerAudioContext.offTimeUpdate",
    "sidebar_label": "InnerAudioContext.offTimeUpdate",
    "source": "api/media/InnerAudioContext/offTimeUpdate.md",
    "permalink": "api/media/InnerAudioContext/offTimeUpdate.html",
    "localized_id": "api/media/InnerAudioContext/offTimeUpdate",
    "language": "en"
  },
  "api/media/InnerAudioContext/offWaiting": {
    "id": "api/media/InnerAudioContext/offWaiting",
    "title": "InnerAudioContext.offWaiting",
    "sidebar_label": "InnerAudioContext.offWaiting",
    "source": "api/media/InnerAudioContext/offWaiting.md",
    "permalink": "api/media/InnerAudioContext/offWaiting.html",
    "localized_id": "api/media/InnerAudioContext/offWaiting",
    "language": "en"
  },
  "api/media/InnerAudioContext/onCanplay": {
    "id": "api/media/InnerAudioContext/onCanplay",
    "title": "InnerAudioContext.onCanplay",
    "sidebar_label": "InnerAudioContext.onCanplay",
    "source": "api/media/InnerAudioContext/onCanplay.md",
    "permalink": "api/media/InnerAudioContext/onCanplay.html",
    "localized_id": "api/media/InnerAudioContext/onCanplay",
    "language": "en"
  },
  "api/media/InnerAudioContext/onEnded": {
    "id": "api/media/InnerAudioContext/onEnded",
    "title": "InnerAudioContext.onEnded",
    "sidebar_label": "InnerAudioContext.onEnded",
    "source": "api/media/InnerAudioContext/onEnded.md",
    "permalink": "api/media/InnerAudioContext/onEnded.html",
    "localized_id": "api/media/InnerAudioContext/onEnded",
    "language": "en"
  },
  "api/media/InnerAudioContext/onError": {
    "id": "api/media/InnerAudioContext/onError",
    "title": "InnerAudioContext.onError",
    "sidebar_label": "InnerAudioContext.onError",
    "source": "api/media/InnerAudioContext/onError.md",
    "permalink": "api/media/InnerAudioContext/onError.html",
    "localized_id": "api/media/InnerAudioContext/onError",
    "language": "en"
  },
  "api/media/InnerAudioContext/onPause": {
    "id": "api/media/InnerAudioContext/onPause",
    "title": "InnerAudioContext.onPause",
    "sidebar_label": "InnerAudioContext.onPause",
    "source": "api/media/InnerAudioContext/onPause.md",
    "permalink": "api/media/InnerAudioContext/onPause.html",
    "localized_id": "api/media/InnerAudioContext/onPause",
    "language": "en"
  },
  "api/media/InnerAudioContext/onPlay": {
    "id": "api/media/InnerAudioContext/onPlay",
    "title": "InnerAudioContext.onPlay",
    "sidebar_label": "InnerAudioContext.onPlay",
    "source": "api/media/InnerAudioContext/onPlay.md",
    "permalink": "api/media/InnerAudioContext/onPlay.html",
    "localized_id": "api/media/InnerAudioContext/onPlay",
    "language": "en"
  },
  "api/media/InnerAudioContext/onSeeked": {
    "id": "api/media/InnerAudioContext/onSeeked",
    "title": "InnerAudioContext.onSeeked",
    "sidebar_label": "InnerAudioContext.onSeeked",
    "source": "api/media/InnerAudioContext/onSeeked.md",
    "permalink": "api/media/InnerAudioContext/onSeeked.html",
    "localized_id": "api/media/InnerAudioContext/onSeeked",
    "language": "en"
  },
  "api/media/InnerAudioContext/onSeeking": {
    "id": "api/media/InnerAudioContext/onSeeking",
    "title": "InnerAudioContext.onSeeking",
    "sidebar_label": "InnerAudioContext.onSeeking",
    "source": "api/media/InnerAudioContext/onSeeking.md",
    "permalink": "api/media/InnerAudioContext/onSeeking.html",
    "localized_id": "api/media/InnerAudioContext/onSeeking",
    "language": "en"
  },
  "api/media/InnerAudioContext/onStop": {
    "id": "api/media/InnerAudioContext/onStop",
    "title": "InnerAudioContext.onStop",
    "sidebar_label": "InnerAudioContext.onStop",
    "source": "api/media/InnerAudioContext/onStop.md",
    "permalink": "api/media/InnerAudioContext/onStop.html",
    "localized_id": "api/media/InnerAudioContext/onStop",
    "language": "en"
  },
  "api/media/InnerAudioContext/onTimeUpdate": {
    "id": "api/media/InnerAudioContext/onTimeUpdate",
    "title": "InnerAudioContext.onTimeUpdate",
    "sidebar_label": "InnerAudioContext.onTimeUpdate",
    "source": "api/media/InnerAudioContext/onTimeUpdate.md",
    "permalink": "api/media/InnerAudioContext/onTimeUpdate.html",
    "localized_id": "api/media/InnerAudioContext/onTimeUpdate",
    "language": "en"
  },
  "api/media/InnerAudioContext/onWaiting": {
    "id": "api/media/InnerAudioContext/onWaiting",
    "title": "InnerAudioContext.onWaiting",
    "sidebar_label": "InnerAudioContext.onWaiting",
    "source": "api/media/InnerAudioContext/onWaiting.md",
    "permalink": "api/media/InnerAudioContext/onWaiting.html",
    "localized_id": "api/media/InnerAudioContext/onWaiting",
    "language": "en"
  },
  "api/media/InnerAudioContext/pause": {
    "id": "api/media/InnerAudioContext/pause",
    "title": "InnerAudioContext.pause",
    "sidebar_label": "InnerAudioContext.pause",
    "source": "api/media/InnerAudioContext/pause.md",
    "permalink": "api/media/InnerAudioContext/pause.html",
    "localized_id": "api/media/InnerAudioContext/pause",
    "language": "en"
  },
  "api/media/InnerAudioContext/play": {
    "id": "api/media/InnerAudioContext/play",
    "title": "InnerAudioContext.play",
    "sidebar_label": "InnerAudioContext.play",
    "source": "api/media/InnerAudioContext/play.md",
    "permalink": "api/media/InnerAudioContext/play.html",
    "localized_id": "api/media/InnerAudioContext/play",
    "language": "en"
  },
  "api/media/InnerAudioContext/seek": {
    "id": "api/media/InnerAudioContext/seek",
    "title": "InnerAudioContext.seek",
    "sidebar_label": "InnerAudioContext.seek",
    "source": "api/media/InnerAudioContext/seek.md",
    "permalink": "api/media/InnerAudioContext/seek.html",
    "localized_id": "api/media/InnerAudioContext/seek",
    "language": "en"
  },
  "api/media/InnerAudioContext/stop": {
    "id": "api/media/InnerAudioContext/stop",
    "title": "InnerAudioContext.stop",
    "sidebar_label": "InnerAudioContext.stop",
    "source": "api/media/InnerAudioContext/stop.md",
    "permalink": "api/media/InnerAudioContext/stop.html",
    "localized_id": "api/media/InnerAudioContext/stop",
    "language": "en"
  },
  "api/media/previewImage": {
    "id": "api/media/previewImage",
    "title": "bl.previewImage",
    "sidebar_label": "bl.previewImage",
    "source": "api/media/previewImage.md",
    "permalink": "api/media/previewImage.html",
    "localized_id": "api/media/previewImage",
    "language": "en"
  },
  "api/media/saveImageToPhotosAlbum": {
    "id": "api/media/saveImageToPhotosAlbum",
    "title": "bl.saveImageToPhotosAlbum",
    "sidebar_label": "bl.saveImageToPhotosAlbum",
    "source": "api/media/saveImageToPhotosAlbum.md",
    "permalink": "api/media/saveImageToPhotosAlbum.html",
    "localized_id": "api/media/saveImageToPhotosAlbum",
    "language": "en"
  },
  "api/media/setInnerAudioOption": {
    "id": "api/media/setInnerAudioOption",
    "title": "bl.setInnerAudioOption",
    "sidebar_label": "bl.setInnerAudioOption",
    "source": "api/media/setInnerAudioOption.md",
    "permalink": "api/media/setInnerAudioOption.html",
    "localized_id": "api/media/setInnerAudioOption",
    "language": "en"
  },
  "api/network/downloadFile": {
    "id": "api/network/downloadFile",
    "title": "bl.downloadFile",
    "sidebar_label": "bl.downloadFile",
    "source": "api/network/downloadFile.md",
    "permalink": "api/network/downloadFile.html",
    "localized_id": "api/network/downloadFile",
    "language": "en"
  },
  "api/network/README": {
    "id": "api/network/README",
    "title": "README",
    "sidebar_label": "README",
    "source": "api/network/README.md",
    "permalink": "api/network/README.html",
    "localized_id": "api/network/README",
    "language": "en"
  },
  "api/network/request": {
    "id": "api/network/request",
    "title": "bl.request",
    "sidebar_label": "bl.request",
    "source": "api/network/request.md",
    "permalink": "api/network/request.html",
    "localized_id": "api/network/request",
    "language": "en"
  },
  "api/network/uploadFile": {
    "id": "api/network/uploadFile",
    "title": "bl.uploadFile",
    "sidebar_label": "bl.uploadFile",
    "source": "api/network/uploadFile.md",
    "permalink": "api/network/uploadFile.html",
    "localized_id": "api/network/uploadFile",
    "language": "en"
  },
  "api/open/authorize": {
    "id": "api/open/authorize",
    "title": "bl.authorize",
    "sidebar_label": "bl.authorize",
    "source": "api/open/authorize.md",
    "permalink": "api/open/authorize.html",
    "localized_id": "api/open/authorize",
    "language": "en"
  },
  "api/open/checkSession": {
    "id": "api/open/checkSession",
    "title": "bl.checkSession",
    "sidebar_label": "bl.checkSession",
    "source": "api/open/checkSession.md",
    "permalink": "api/open/checkSession.html",
    "localized_id": "api/open/checkSession",
    "language": "en"
  },
  "api/open/chooseAddress": {
    "id": "api/open/chooseAddress",
    "title": "bl.chooseAddress",
    "sidebar_label": "bl.chooseAddress",
    "source": "api/open/chooseAddress.md",
    "permalink": "api/open/chooseAddress.html",
    "localized_id": "api/open/chooseAddress",
    "language": "en"
  },
  "api/open/getAccountInfo": {
    "id": "api/open/getAccountInfo",
    "title": "bl.getAccountInfo",
    "sidebar_label": "bl.getAccountInfo",
    "source": "api/open/getAccountInfo.md",
    "permalink": "api/open/getAccountInfo.html",
    "localized_id": "api/open/getAccountInfo",
    "language": "en"
  },
  "api/open/getAccountInfoSync": {
    "id": "api/open/getAccountInfoSync",
    "title": "bl.getAccountInfoSync",
    "sidebar_label": "bl.getAccountInfoSync",
    "source": "api/open/getAccountInfoSync.md",
    "permalink": "api/open/getAccountInfoSync.html",
    "localized_id": "api/open/getAccountInfoSync",
    "language": "en"
  },
  "api/open/getFollowUpperStatus": {
    "id": "api/open/getFollowUpperStatus",
    "title": "bl.getFollowUpperStatus",
    "sidebar_label": "bl.getFollowUpperStatus",
    "source": "api/open/getFollowUpperStatus.md",
    "permalink": "api/open/getFollowUpperStatus.html",
    "localized_id": "api/open/getFollowUpperStatus",
    "language": "en"
  },
  "api/open/getLaunchOptions2": {
    "id": "api/open/getLaunchOptions2",
    "title": "bl.getLaunchOptions2",
    "sidebar_label": "bl.getLaunchOptions2",
    "source": "api/open/getLaunchOptions2.md",
    "permalink": "api/open/getLaunchOptions2.html",
    "localized_id": "api/open/getLaunchOptions2",
    "language": "en"
  },
  "api/open/getSetting": {
    "id": "api/open/getSetting",
    "title": "bl.getSetting",
    "sidebar_label": "bl.getSetting",
    "source": "api/open/getSetting.md",
    "permalink": "api/open/getSetting.html",
    "localized_id": "api/open/getSetting",
    "language": "en"
  },
  "api/open/getUserInfo": {
    "id": "api/open/getUserInfo",
    "title": "bl.getUserInfo",
    "sidebar_label": "bl.getUserInfo",
    "source": "api/open/getUserInfo.md",
    "permalink": "api/open/getUserInfo.html",
    "localized_id": "api/open/getUserInfo",
    "language": "en"
  },
  "api/open/login": {
    "id": "api/open/login",
    "title": "bl.login",
    "sidebar_label": "bl.login",
    "source": "api/open/login.md",
    "permalink": "api/open/login.html",
    "localized_id": "api/open/login",
    "language": "en"
  },
  "api/open/openSetting": {
    "id": "api/open/openSetting",
    "title": "bl.openSetting",
    "sidebar_label": "bl.openSetting",
    "source": "api/open/openSetting.md",
    "permalink": "api/open/openSetting.html",
    "localized_id": "api/open/openSetting",
    "language": "en"
  },
  "api/open/requestPayment": {
    "id": "api/open/requestPayment",
    "title": "bl.requestPayment",
    "sidebar_label": "bl.requestPayment",
    "source": "api/open/requestPayment.md",
    "permalink": "api/open/requestPayment.html",
    "localized_id": "api/open/requestPayment",
    "language": "en"
  },
  "api/open/share": {
    "id": "api/open/share",
    "title": "bl.share",
    "sidebar_label": "bl.share",
    "source": "api/open/share.md",
    "permalink": "api/open/share.html",
    "localized_id": "api/open/share",
    "language": "en"
  },
  "api/api": {
    "id": "api/api",
    "title": "使用说明",
    "sidebar_label": "使用说明",
    "source": "api/README.md",
    "permalink": "api/api.html",
    "localized_id": "api/api",
    "language": "en"
  },
  "api/storage/clearStorage": {
    "id": "api/storage/clearStorage",
    "title": "bl.clearStorage",
    "sidebar_label": "bl.clearStorage",
    "source": "api/storage/clearStorage.md",
    "permalink": "api/storage/clearStorage.html",
    "localized_id": "api/storage/clearStorage",
    "language": "en"
  },
  "api/storage/clearStorageSync": {
    "id": "api/storage/clearStorageSync",
    "title": "bl.clearStorageSync",
    "sidebar_label": "bl.clearStorageSync",
    "source": "api/storage/clearStorageSync.md",
    "permalink": "api/storage/clearStorageSync.html",
    "localized_id": "api/storage/clearStorageSync",
    "language": "en"
  },
  "api/storage/getStorage": {
    "id": "api/storage/getStorage",
    "title": "bl.getStorage",
    "sidebar_label": "bl.getStorage",
    "source": "api/storage/getStorage.md",
    "permalink": "api/storage/getStorage.html",
    "localized_id": "api/storage/getStorage",
    "language": "en"
  },
  "api/storage/getStorageInfo": {
    "id": "api/storage/getStorageInfo",
    "title": "bl.getStorageInfo",
    "sidebar_label": "bl.getStorageInfo",
    "source": "api/storage/getStorageInfo.md",
    "permalink": "api/storage/getStorageInfo.html",
    "localized_id": "api/storage/getStorageInfo",
    "language": "en"
  },
  "api/storage/getStorageInfoSync": {
    "id": "api/storage/getStorageInfoSync",
    "title": "bl.getStorageInfoSync",
    "sidebar_label": "bl.getStorageInfoSync",
    "source": "api/storage/getStorageInfoSync.md",
    "permalink": "api/storage/getStorageInfoSync.html",
    "localized_id": "api/storage/getStorageInfoSync",
    "language": "en"
  },
  "api/storage/getStorageSync": {
    "id": "api/storage/getStorageSync",
    "title": "bl.getStorageSync",
    "sidebar_label": "bl.getStorageSync",
    "source": "api/storage/getStorageSync.md",
    "permalink": "api/storage/getStorageSync.html",
    "localized_id": "api/storage/getStorageSync",
    "language": "en"
  },
  "api/storage/README": {
    "id": "api/storage/README",
    "title": "README",
    "sidebar_label": "README",
    "source": "api/storage/README.md",
    "permalink": "api/storage/README.html",
    "localized_id": "api/storage/README",
    "language": "en"
  },
  "api/storage/removeStorage": {
    "id": "api/storage/removeStorage",
    "title": "bl.removeStorage",
    "sidebar_label": "bl.removeStorage",
    "source": "api/storage/removeStorage.md",
    "permalink": "api/storage/removeStorage.html",
    "localized_id": "api/storage/removeStorage",
    "language": "en"
  },
  "api/storage/removeStorageSync": {
    "id": "api/storage/removeStorageSync",
    "title": "bl.removeStorageSync",
    "sidebar_label": "bl.removeStorageSync",
    "source": "api/storage/removeStorageSync.md",
    "permalink": "api/storage/removeStorageSync.html",
    "localized_id": "api/storage/removeStorageSync",
    "language": "en"
  },
  "api/storage/setStorage": {
    "id": "api/storage/setStorage",
    "title": "bl.setStorage",
    "sidebar_label": "bl.setStorage",
    "source": "api/storage/setStorage.md",
    "permalink": "api/storage/setStorage.html",
    "localized_id": "api/storage/setStorage",
    "language": "en"
  },
  "api/storage/setStorageSync": {
    "id": "api/storage/setStorageSync",
    "title": "bl.setStorageSync",
    "sidebar_label": "bl.setStorageSync",
    "source": "api/storage/setStorageSync.md",
    "permalink": "api/storage/setStorageSync.html",
    "localized_id": "api/storage/setStorageSync",
    "language": "en"
  },
  "api/ui/hideLoading": {
    "id": "api/ui/hideLoading",
    "title": "bl.hideLoading",
    "sidebar_label": "bl.hideLoading",
    "source": "api/ui/hideLoading.md",
    "permalink": "api/ui/hideLoading.html",
    "localized_id": "api/ui/hideLoading",
    "language": "en"
  },
  "api/ui/hideNavigationBarLoading": {
    "id": "api/ui/hideNavigationBarLoading",
    "title": "bl.hideNavigationBarLoading",
    "sidebar_label": "bl.hideNavigationBarLoading",
    "source": "api/ui/hideNavigationBarLoading.md",
    "permalink": "api/ui/hideNavigationBarLoading.html",
    "localized_id": "api/ui/hideNavigationBarLoading",
    "language": "en"
  },
  "api/ui/hideNavigationLeftButton": {
    "id": "api/ui/hideNavigationLeftButton",
    "title": "bl.hideNavigationLeftButton",
    "sidebar_label": "bl.hideNavigationLeftButton",
    "source": "api/ui/hideNavigationLeftButton.md",
    "permalink": "api/ui/hideNavigationLeftButton.html",
    "localized_id": "api/ui/hideNavigationLeftButton",
    "language": "en"
  },
  "api/ui/hideTabBar": {
    "id": "api/ui/hideTabBar",
    "title": "bl.hideTabBar",
    "sidebar_label": "bl.hideTabBar",
    "source": "api/ui/hideTabBar.md",
    "permalink": "api/ui/hideTabBar.html",
    "localized_id": "api/ui/hideTabBar",
    "language": "en"
  },
  "api/ui/hideTabBarRedDot": {
    "id": "api/ui/hideTabBarRedDot",
    "title": "bl.hideTabBarRedDot",
    "sidebar_label": "bl.hideTabBarRedDot",
    "source": "api/ui/hideTabBarRedDot.md",
    "permalink": "api/ui/hideTabBarRedDot.html",
    "localized_id": "api/ui/hideTabBarRedDot",
    "language": "en"
  },
  "api/ui/hideToast": {
    "id": "api/ui/hideToast",
    "title": "bl.hideToast",
    "sidebar_label": "bl.hideToast",
    "source": "api/ui/hideToast.md",
    "permalink": "api/ui/hideToast.html",
    "localized_id": "api/ui/hideToast",
    "language": "en"
  },
  "api/ui/navigateBack": {
    "id": "api/ui/navigateBack",
    "title": "bl.navigateBack",
    "sidebar_label": "bl.navigateBack",
    "source": "api/ui/navigateBack.md",
    "permalink": "api/ui/navigateBack.html",
    "localized_id": "api/ui/navigateBack",
    "language": "en"
  },
  "api/ui/navigateTo": {
    "id": "api/ui/navigateTo",
    "title": "bl.navigateTo",
    "sidebar_label": "bl.navigateTo",
    "source": "api/ui/navigateTo.md",
    "permalink": "api/ui/navigateTo.html",
    "localized_id": "api/ui/navigateTo",
    "language": "en"
  },
  "api/ui/navigateToMiniProgram": {
    "id": "api/ui/navigateToMiniProgram",
    "title": "bl.navigateToMiniProgram",
    "sidebar_label": "bl.navigateToMiniProgram",
    "source": "api/ui/navigateToMiniProgram.md",
    "permalink": "api/ui/navigateToMiniProgram.html",
    "localized_id": "api/ui/navigateToMiniProgram",
    "language": "en"
  },
  "api/ui/offWindowResize": {
    "id": "api/ui/offWindowResize",
    "title": "bl.offWindowResize",
    "sidebar_label": "bl.offWindowResize",
    "source": "api/ui/offWindowResize.md",
    "permalink": "api/ui/offWindowResize.html",
    "localized_id": "api/ui/offWindowResize",
    "language": "en"
  },
  "api/ui/onPullDownRefresh": {
    "id": "api/ui/onPullDownRefresh",
    "title": "bl.onPullDownRefresh",
    "sidebar_label": "bl.onPullDownRefresh",
    "source": "api/ui/onPullDownRefresh.md",
    "permalink": "api/ui/onPullDownRefresh.html",
    "localized_id": "api/ui/onPullDownRefresh",
    "language": "en"
  },
  "api/ui/onWindowResize": {
    "id": "api/ui/onWindowResize",
    "title": "bl.onWindowResize",
    "sidebar_label": "bl.onWindowResize",
    "source": "api/ui/onWindowResize.md",
    "permalink": "api/ui/onWindowResize.html",
    "localized_id": "api/ui/onWindowResize",
    "language": "en"
  },
  "api/ui/pageScrollTo": {
    "id": "api/ui/pageScrollTo",
    "title": "bl.pageScrollTo",
    "sidebar_label": "bl.pageScrollTo",
    "source": "api/ui/pageScrollTo.md",
    "permalink": "api/ui/pageScrollTo.html",
    "localized_id": "api/ui/pageScrollTo",
    "language": "en"
  },
  "api/ui/README": {
    "id": "api/ui/README",
    "title": "README",
    "sidebar_label": "README",
    "source": "api/ui/README.md",
    "permalink": "api/ui/README.html",
    "localized_id": "api/ui/README",
    "language": "en"
  },
  "api/ui/redirectTo": {
    "id": "api/ui/redirectTo",
    "title": "bl.redirectTo",
    "sidebar_label": "bl.redirectTo",
    "source": "api/ui/redirectTo.md",
    "permalink": "api/ui/redirectTo.html",
    "localized_id": "api/ui/redirectTo",
    "language": "en"
  },
  "api/ui/removeTabBarBadge": {
    "id": "api/ui/removeTabBarBadge",
    "title": "bl.removeTabBarBadge",
    "sidebar_label": "bl.removeTabBarBadge",
    "source": "api/ui/removeTabBarBadge.md",
    "permalink": "api/ui/removeTabBarBadge.html",
    "localized_id": "api/ui/removeTabBarBadge",
    "language": "en"
  },
  "api/ui/setBackgroundColor": {
    "id": "api/ui/setBackgroundColor",
    "title": "bl.setBackgroundColor",
    "sidebar_label": "bl.setBackgroundColor",
    "source": "api/ui/setBackgroundColor.md",
    "permalink": "api/ui/setBackgroundColor.html",
    "localized_id": "api/ui/setBackgroundColor",
    "language": "en"
  },
  "api/ui/setBackgroundTextStyle": {
    "id": "api/ui/setBackgroundTextStyle",
    "title": "bl.setBackgroundTextStyle",
    "sidebar_label": "bl.setBackgroundTextStyle",
    "source": "api/ui/setBackgroundTextStyle.md",
    "permalink": "api/ui/setBackgroundTextStyle.html",
    "localized_id": "api/ui/setBackgroundTextStyle",
    "language": "en"
  },
  "api/ui/setNavigationBarColor": {
    "id": "api/ui/setNavigationBarColor",
    "title": "bl.setNavigationBarColor",
    "sidebar_label": "bl.setNavigationBarColor",
    "source": "api/ui/setNavigationBarColor.md",
    "permalink": "api/ui/setNavigationBarColor.html",
    "localized_id": "api/ui/setNavigationBarColor",
    "language": "en"
  },
  "api/ui/setNavigationBarTitle": {
    "id": "api/ui/setNavigationBarTitle",
    "title": "bl.setNavigationBarTitle",
    "sidebar_label": "bl.setNavigationBarTitle",
    "source": "api/ui/setNavigationBarTitle.md",
    "permalink": "api/ui/setNavigationBarTitle.html",
    "localized_id": "api/ui/setNavigationBarTitle",
    "language": "en"
  },
  "api/ui/setStatusBarStyle": {
    "id": "api/ui/setStatusBarStyle",
    "title": "bl.setStatusBarStyle",
    "sidebar_label": "bl.setStatusBarStyle",
    "source": "api/ui/setStatusBarStyle.md",
    "permalink": "api/ui/setStatusBarStyle.html",
    "localized_id": "api/ui/setStatusBarStyle",
    "language": "en"
  },
  "api/ui/setTabBarBadge": {
    "id": "api/ui/setTabBarBadge",
    "title": "bl.setTabBarBadge",
    "sidebar_label": "bl.setTabBarBadge",
    "source": "api/ui/setTabBarBadge.md",
    "permalink": "api/ui/setTabBarBadge.html",
    "localized_id": "api/ui/setTabBarBadge",
    "language": "en"
  },
  "api/ui/setTabBarItem": {
    "id": "api/ui/setTabBarItem",
    "title": "bl.setTabBarItem",
    "sidebar_label": "bl.setTabBarItem",
    "source": "api/ui/setTabBarItem.md",
    "permalink": "api/ui/setTabBarItem.html",
    "localized_id": "api/ui/setTabBarItem",
    "language": "en"
  },
  "api/ui/setTabBarStyle": {
    "id": "api/ui/setTabBarStyle",
    "title": "bl.setTabBarStyle",
    "sidebar_label": "bl.setTabBarStyle",
    "source": "api/ui/setTabBarStyle.md",
    "permalink": "api/ui/setTabBarStyle.html",
    "localized_id": "api/ui/setTabBarStyle",
    "language": "en"
  },
  "api/ui/showActionSheet": {
    "id": "api/ui/showActionSheet",
    "title": "bl.showActionSheet",
    "sidebar_label": "bl.showActionSheet",
    "source": "api/ui/showActionSheet.md",
    "permalink": "api/ui/showActionSheet.html",
    "localized_id": "api/ui/showActionSheet",
    "language": "en"
  },
  "api/ui/showLoading": {
    "id": "api/ui/showLoading",
    "title": "bl.showLoading",
    "sidebar_label": "bl.showLoading",
    "source": "api/ui/showLoading.md",
    "permalink": "api/ui/showLoading.html",
    "localized_id": "api/ui/showLoading",
    "language": "en"
  },
  "api/ui/showModal": {
    "id": "api/ui/showModal",
    "title": "bl.showModal",
    "sidebar_label": "bl.showModal",
    "source": "api/ui/showModal.md",
    "permalink": "api/ui/showModal.html",
    "localized_id": "api/ui/showModal",
    "language": "en"
  },
  "api/ui/showNavigationBarLoading": {
    "id": "api/ui/showNavigationBarLoading",
    "title": "bl.showNavigationBarLoading",
    "sidebar_label": "bl.showNavigationBarLoading",
    "source": "api/ui/showNavigationBarLoading.md",
    "permalink": "api/ui/showNavigationBarLoading.html",
    "localized_id": "api/ui/showNavigationBarLoading",
    "language": "en"
  },
  "api/ui/showNavigationLeftButton": {
    "id": "api/ui/showNavigationLeftButton",
    "title": "bl.showNavigationLeftButton",
    "sidebar_label": "bl.showNavigationLeftButton",
    "source": "api/ui/showNavigationLeftButton.md",
    "permalink": "api/ui/showNavigationLeftButton.html",
    "localized_id": "api/ui/showNavigationLeftButton",
    "language": "en"
  },
  "api/ui/showTabBar": {
    "id": "api/ui/showTabBar",
    "title": "bl.showTabBar",
    "sidebar_label": "bl.showTabBar",
    "source": "api/ui/showTabBar.md",
    "permalink": "api/ui/showTabBar.html",
    "localized_id": "api/ui/showTabBar",
    "language": "en"
  },
  "api/ui/showTabBarRedDot": {
    "id": "api/ui/showTabBarRedDot",
    "title": "bl.showTabBarRedDot",
    "sidebar_label": "bl.showTabBarRedDot",
    "source": "api/ui/showTabBarRedDot.md",
    "permalink": "api/ui/showTabBarRedDot.html",
    "localized_id": "api/ui/showTabBarRedDot",
    "language": "en"
  },
  "api/ui/showToast": {
    "id": "api/ui/showToast",
    "title": "bl.showToast",
    "sidebar_label": "bl.showToast",
    "source": "api/ui/showToast.md",
    "permalink": "api/ui/showToast.html",
    "localized_id": "api/ui/showToast",
    "language": "en"
  },
  "api/ui/startPullDownRefresh": {
    "id": "api/ui/startPullDownRefresh",
    "title": "bl.startPullDownRefresh",
    "sidebar_label": "bl.startPullDownRefresh",
    "source": "api/ui/startPullDownRefresh.md",
    "permalink": "api/ui/startPullDownRefresh.html",
    "localized_id": "api/ui/startPullDownRefresh",
    "language": "en"
  },
  "api/ui/stopPullDownRefresh": {
    "id": "api/ui/stopPullDownRefresh",
    "title": "bl.stopPullDownRefresh",
    "sidebar_label": "bl.stopPullDownRefresh",
    "source": "api/ui/stopPullDownRefresh.md",
    "permalink": "api/ui/stopPullDownRefresh.html",
    "localized_id": "api/ui/stopPullDownRefresh",
    "language": "en"
  },
  "api/ui/switchTab": {
    "id": "api/ui/switchTab",
    "title": "bl.switchTab",
    "sidebar_label": "bl.switchTab",
    "source": "api/ui/switchTab.md",
    "permalink": "api/ui/switchTab.html",
    "localized_id": "api/ui/switchTab",
    "language": "en"
  },
  "component/audio": {
    "id": "component/audio",
    "source": "component/audio.md",
    "title": "component/audio",
    "permalink": "component/audio.html",
    "localized_id": "component/audio",
    "language": "en"
  },
  "component/button": {
    "id": "component/button",
    "source": "component/button.md",
    "title": "component/button",
    "permalink": "component/button.html",
    "localized_id": "component/button",
    "language": "en"
  },
  "component/camera": {
    "id": "component/camera",
    "source": "component/camera.md",
    "title": "component/camera",
    "permalink": "component/camera.html",
    "localized_id": "component/camera",
    "language": "en"
  },
  "component/canvas": {
    "id": "component/canvas",
    "source": "component/canvas.md",
    "title": "component/canvas",
    "permalink": "component/canvas.html",
    "localized_id": "component/canvas",
    "language": "en"
  },
  "component/checkbox": {
    "id": "component/checkbox",
    "title": "checkbox",
    "sidebar_label": "checkbox",
    "source": "component/checkbox.md",
    "permalink": "component/checkbox.html",
    "localized_id": "component/checkbox",
    "language": "en"
  },
  "component/cover-view": {
    "id": "component/cover-view",
    "source": "component/cover-view.md",
    "title": "component/cover-view",
    "permalink": "component/cover-view.html",
    "localized_id": "component/cover-view",
    "language": "en"
  },
  "component/follow": {
    "id": "component/follow",
    "title": "follow",
    "sidebar_label": "follow",
    "source": "component/follow.md",
    "permalink": "component/follow.html",
    "localized_id": "component/follow",
    "language": "en"
  },
  "component/form": {
    "id": "component/form",
    "title": "form",
    "sidebar_label": "form",
    "source": "component/form.md",
    "permalink": "component/form.html",
    "localized_id": "component/form",
    "language": "en"
  },
  "component/icon": {
    "id": "component/icon",
    "title": "b-icon",
    "sidebar_label": "b-icon",
    "source": "component/icon.md",
    "permalink": "component/icon.html",
    "localized_id": "component/icon",
    "language": "en"
  },
  "component/image": {
    "id": "component/image",
    "title": "b-image",
    "sidebar_label": "b-image",
    "source": "component/image.md",
    "permalink": "component/image.html",
    "localized_id": "component/image",
    "language": "en"
  },
  "component/input": {
    "id": "component/input",
    "title": "b-input",
    "sidebar_label": "b-input",
    "source": "component/input.md",
    "permalink": "component/input.html",
    "localized_id": "component/input",
    "language": "en"
  },
  "component/label": {
    "id": "component/label",
    "title": "label",
    "sidebar_label": "label",
    "source": "component/label.md",
    "permalink": "component/label.html",
    "localized_id": "component/label",
    "language": "en"
  },
  "component/map": {
    "id": "component/map",
    "source": "component/map.md",
    "title": "component/map",
    "permalink": "component/map.html",
    "localized_id": "component/map",
    "language": "en"
  },
  "component/movable-view": {
    "id": "component/movable-view",
    "source": "component/movable-view.md",
    "title": "component/movable-view",
    "permalink": "component/movable-view.html",
    "localized_id": "component/movable-view",
    "language": "en"
  },
  "component/native": {
    "id": "component/native",
    "title": "原生组件说明",
    "sidebar_label": "原生组件说明",
    "source": "component/native.md",
    "permalink": "component/native.html",
    "localized_id": "component/native",
    "language": "en"
  },
  "component/navigator": {
    "id": "component/navigator",
    "source": "component/navigator.md",
    "title": "component/navigator",
    "permalink": "component/navigator.html",
    "localized_id": "component/navigator",
    "language": "en"
  },
  "component/open-data": {
    "id": "component/open-data",
    "source": "component/open-data.md",
    "title": "component/open-data",
    "permalink": "component/open-data.html",
    "localized_id": "component/open-data",
    "language": "en"
  },
  "component/picker-view": {
    "id": "component/picker-view",
    "source": "component/picker-view.md",
    "title": "component/picker-view",
    "permalink": "component/picker-view.html",
    "localized_id": "component/picker-view",
    "language": "en"
  },
  "component/picker": {
    "id": "component/picker",
    "title": "picker",
    "sidebar_label": "picker",
    "source": "component/picker.md",
    "permalink": "component/picker.html",
    "localized_id": "component/picker",
    "language": "en"
  },
  "component/progress": {
    "id": "component/progress",
    "title": "b-progress",
    "sidebar_label": "b-progress",
    "source": "component/progress.md",
    "permalink": "component/progress.html",
    "localized_id": "component/progress",
    "language": "en"
  },
  "component/radio": {
    "id": "component/radio",
    "title": "radio",
    "sidebar_label": "radio",
    "source": "component/radio.md",
    "permalink": "component/radio.html",
    "localized_id": "component/radio",
    "language": "en"
  },
  "component/component": {
    "id": "component/component",
    "title": "使用说明",
    "sidebar_label": "使用说明",
    "source": "component/README.md",
    "permalink": "component/component.html",
    "localized_id": "component/component",
    "language": "en"
  },
  "component/rich-text": {
    "id": "component/rich-text",
    "title": "rich-text",
    "sidebar_label": "rich-text",
    "source": "component/rich-text.md",
    "permalink": "component/rich-text.html",
    "localized_id": "component/rich-text",
    "language": "en"
  },
  "component/scroll-view": {
    "id": "component/scroll-view",
    "title": "scroll-view",
    "sidebar_label": "scroll-view",
    "source": "component/scroll-view.md",
    "permalink": "component/scroll-view.html",
    "localized_id": "component/scroll-view",
    "language": "en"
  },
  "component/slider": {
    "id": "component/slider",
    "title": "b-slider",
    "sidebar_label": "b-slider",
    "source": "component/slider.md",
    "permalink": "component/slider.html",
    "localized_id": "component/slider",
    "language": "en"
  },
  "component/swiper": {
    "id": "component/swiper",
    "title": "swiper",
    "sidebar_label": "swiper",
    "source": "component/swiper.md",
    "permalink": "component/swiper.html",
    "localized_id": "component/swiper",
    "language": "en"
  },
  "component/switch": {
    "id": "component/switch",
    "title": "b-switch",
    "sidebar_label": "b-switch",
    "source": "component/switch.md",
    "permalink": "component/switch.html",
    "localized_id": "component/switch",
    "language": "en"
  },
  "component/text": {
    "id": "component/text",
    "source": "component/text.md",
    "title": "component/text",
    "permalink": "component/text.html",
    "localized_id": "component/text",
    "language": "en"
  },
  "component/textarea": {
    "id": "component/textarea",
    "title": "b-textarea",
    "sidebar_label": "b-textarea",
    "source": "component/textarea.md",
    "permalink": "component/textarea.html",
    "localized_id": "component/textarea",
    "language": "en"
  },
  "component/video": {
    "id": "component/video",
    "source": "component/video.md",
    "title": "component/video",
    "permalink": "component/video.html",
    "localized_id": "component/video",
    "language": "en"
  },
  "component/view": {
    "id": "component/view",
    "title": "view",
    "sidebar_label": "view",
    "source": "component/view.md",
    "permalink": "component/view.html",
    "localized_id": "component/view",
    "language": "en"
  },
  "component/web-view": {
    "id": "component/web-view",
    "title": "web-view",
    "sidebar_label": "web-view",
    "source": "component/web-view.md",
    "permalink": "component/web-view.html",
    "localized_id": "component/web-view",
    "language": "en"
  },
  "framework/api": {
    "id": "framework/api",
    "title": "API",
    "sidebar_label": "API",
    "source": "framework/api.md",
    "permalink": "framework/api.html",
    "localized_id": "framework/api",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 8,
    "next_id": "framework/difference",
    "next": "framework/difference",
    "previous_id": "framework/router",
    "previous": "framework/router",
    "previous_title": "页面路由",
    "next_title": "与微信小程序的差异"
  },
  "framework/difference": {
    "id": "framework/difference",
    "title": "与微信小程序的差异",
    "sidebar_label": "与微信小程序的差异",
    "source": "framework/difference.md",
    "permalink": "framework/difference.html",
    "localized_id": "framework/difference",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 9,
    "next_id": "framework/vue",
    "next": "framework/vue",
    "previous_id": "framework/api",
    "previous": "framework/api",
    "previous_title": "API",
    "next_title": "使用Vue的限制"
  },
  "framework/global-config": {
    "id": "framework/global-config",
    "title": "全局配置",
    "sidebar_label": "全局配置",
    "source": "framework/global-config.md",
    "permalink": "framework/global-config.html",
    "localized_id": "framework/global-config",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 4,
    "next_id": "framework/register-app",
    "next": "framework/register-app",
    "previous_id": "framework/structure",
    "previous": "framework/structure",
    "previous_title": "目录结构",
    "next_title": "小程序 App"
  },
  "framework/framework": {
    "id": "framework/framework",
    "title": "框架",
    "sidebar_label": "概述",
    "source": "framework/README.md",
    "permalink": "framework/framework.html",
    "localized_id": "framework/framework",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 2,
    "next_id": "framework/structure",
    "next": "framework/structure",
    "previous_id": "guide/guide",
    "previous": "guide/guide",
    "previous_title": "快速开始",
    "next_title": "目录结构"
  },
  "framework/register-app": {
    "id": "framework/register-app",
    "title": "小程序 App",
    "sidebar_label": "小程序 App",
    "source": "framework/register-app.md",
    "permalink": "framework/register-app.html",
    "localized_id": "framework/register-app",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 5,
    "next_id": "framework/register-page",
    "next": "framework/register-page",
    "previous_id": "framework/global-config",
    "previous": "framework/global-config",
    "previous_title": "全局配置",
    "next_title": "页面 Page"
  },
  "framework/register-page": {
    "id": "framework/register-page",
    "title": "页面 Page",
    "sidebar_label": "页面 Page",
    "source": "framework/register-page.md",
    "permalink": "framework/register-page.html",
    "localized_id": "framework/register-page",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 6,
    "next_id": "framework/router",
    "next": "framework/router",
    "previous_id": "framework/register-app",
    "previous": "framework/register-app",
    "previous_title": "小程序 App",
    "next_title": "页面路由"
  },
  "framework/router": {
    "id": "framework/router",
    "title": "页面路由",
    "sidebar_label": "页面路由",
    "source": "framework/router.md",
    "permalink": "framework/router.html",
    "localized_id": "framework/router",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 7,
    "next_id": "framework/api",
    "next": "framework/api",
    "previous_id": "framework/register-page",
    "previous": "framework/register-page",
    "previous_title": "页面 Page",
    "next_title": "API"
  },
  "framework/structure": {
    "id": "framework/structure",
    "title": "目录结构",
    "sidebar_label": "目录结构",
    "source": "framework/structure.md",
    "permalink": "framework/structure.html",
    "localized_id": "framework/structure",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 3,
    "next_id": "framework/global-config",
    "next": "framework/global-config",
    "previous_id": "framework/framework",
    "previous": "framework/framework",
    "previous_title": "框架",
    "next_title": "全局配置"
  },
  "framework/vue": {
    "id": "framework/vue",
    "title": "使用Vue的限制",
    "sidebar_label": "使用Vue的限制",
    "source": "framework/vue.md",
    "permalink": "framework/vue.html",
    "localized_id": "framework/vue",
    "language": "en",
    "sidebar": "guide",
    "category": "框架",
    "subcategory": null,
    "order": 10,
    "next_id": "ability/network",
    "next": "ability/network",
    "previous_id": "framework/difference",
    "previous": "framework/difference",
    "previous_title": "与微信小程序的差异",
    "next_title": "网络"
  },
  "guide/guide": {
    "id": "guide/guide",
    "title": "快速开始",
    "sidebar_label": "快速开始",
    "source": "guide/README.md",
    "permalink": "guide/guide.html",
    "localized_id": "guide/guide",
    "language": "en",
    "sidebar": "guide",
    "category": "指南",
    "subcategory": null,
    "order": 1,
    "directLink": true,
    "level": 2,
    "next_id": "framework/framework",
    "next": "framework/framework",
    "next_title": "框架"
  },
  "lib/baseVersionSetting": {
    "id": "lib/baseVersionSetting",
    "source": "lib/baseVersionSetting.md",
    "title": "lib/baseVersionSetting",
    "permalink": "lib/baseVersionSetting.html",
    "localized_id": "lib/baseVersionSetting",
    "language": "en"
  },
  "lib/log": {
    "id": "lib/log",
    "source": "lib/log.md",
    "title": "lib/log",
    "permalink": "lib/log.html",
    "localized_id": "lib/log",
    "language": "en"
  },
  "lib/relation": {
    "id": "lib/relation",
    "source": "lib/relation.md",
    "title": "lib/relation",
    "permalink": "lib/relation.html",
    "localized_id": "lib/relation",
    "language": "en"
  },
  "open/authorize": {
    "id": "open/authorize",
    "title": "授权",
    "sidebar_label": "授权",
    "source": "open/authorize.md",
    "permalink": "open/authorize.html",
    "localized_id": "open/authorize",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": null,
    "order": 15,
    "next_id": "open/share",
    "next": "open/share",
    "previous_id": "open/signature",
    "previous": "open/signature",
    "previous_title": "开放数据校验与解密",
    "next_title": "转发"
  },
  "open/data-analysis": {
    "id": "open/data-analysis",
    "source": "open/data-analysis.md",
    "title": "open/data-analysis",
    "permalink": "open/data-analysis.html",
    "localized_id": "open/data-analysis",
    "language": "en"
  },
  "open/login": {
    "id": "open/login",
    "title": "小程序登录",
    "sidebar_label": "小程序登录",
    "source": "open/login.md",
    "permalink": "open/login.html",
    "localized_id": "open/login",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": null,
    "order": 13,
    "next_id": "open/signature",
    "next": "open/signature",
    "previous_id": "ability/storage",
    "previous": "ability/storage",
    "previous_title": "存储",
    "next_title": "开放数据校验与解密"
  },
  "open/material/material-delete": {
    "id": "open/material/material-delete",
    "title": "删除素材接口",
    "sidebar_label": "删除素材接口",
    "source": "open/material/material-delete.md",
    "permalink": "open/material/material-delete.html",
    "localized_id": "open/material/material-delete",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "素材",
    "order": 27,
    "next_id": "open/material/material-query",
    "next": "open/material/material-query",
    "previous_id": "open/material/material-upload",
    "previous": "open/material/material-upload",
    "previous_title": "上传素材到素材库",
    "next_title": "查询素材接口"
  },
  "open/material/material-link-delete": {
    "id": "open/material/material-link-delete",
    "title": "素材取消关联接口",
    "sidebar_label": "素材取消关联接口",
    "source": "open/material/material-link-delete.md",
    "permalink": "open/material/material-link-delete.html",
    "localized_id": "open/material/material-link-delete",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "素材",
    "order": 30,
    "next_id": "open/material/material-link-query",
    "next": "open/material/material-link-query",
    "previous_id": "open/material/material-link",
    "previous": "open/material/material-link",
    "previous_title": "素材关联接口",
    "next_title": "查询素材关联接口"
  },
  "open/material/material-link-query": {
    "id": "open/material/material-link-query",
    "title": "查询素材关联接口",
    "sidebar_label": "查询素材关联接口",
    "source": "open/material/material-link-query.md",
    "permalink": "open/material/material-link-query.html",
    "localized_id": "open/material/material-link-query",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "素材",
    "order": 31,
    "previous_id": "open/material/material-link-delete",
    "previous": "open/material/material-link-delete",
    "previous_title": "素材取消关联接口"
  },
  "open/material/material-link": {
    "id": "open/material/material-link",
    "title": "素材关联接口",
    "sidebar_label": "素材关联接口",
    "source": "open/material/material-link.md",
    "permalink": "open/material/material-link.html",
    "localized_id": "open/material/material-link",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "素材",
    "order": 29,
    "next_id": "open/material/material-link-delete",
    "next": "open/material/material-link-delete",
    "previous_id": "open/material/material-query",
    "previous": "open/material/material-query",
    "previous_title": "查询素材接口",
    "next_title": "素材取消关联接口"
  },
  "open/material/material-query": {
    "id": "open/material/material-query",
    "title": "查询素材接口",
    "sidebar_label": "查询素材接口",
    "source": "open/material/material-query.md",
    "permalink": "open/material/material-query.html",
    "localized_id": "open/material/material-query",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "素材",
    "order": 28,
    "next_id": "open/material/material-link",
    "next": "open/material/material-link",
    "previous_id": "open/material/material-delete",
    "previous": "open/material/material-delete",
    "previous_title": "删除素材接口",
    "next_title": "素材关联接口"
  },
  "open/material/material-upload": {
    "id": "open/material/material-upload",
    "title": "上传素材到素材库",
    "sidebar_label": "上传素材到素材库",
    "source": "open/material/material-upload.md",
    "permalink": "open/material/material-upload.html",
    "localized_id": "open/material/material-upload",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "素材",
    "order": 26,
    "next_id": "open/material/material-delete",
    "next": "open/material/material-delete",
    "previous_id": "open/pay/query-declare",
    "previous": "open/pay/query-declare",
    "previous_title": "2.4 海关申报查询接口",
    "next_title": "删除素材接口"
  },
  "open/pay": {
    "id": "open/pay",
    "title": "支付",
    "sidebar_label": "支付",
    "source": "open/pay.md",
    "permalink": "open/pay.html",
    "localized_id": "open/pay",
    "language": "en"
  },
  "open/pay/add-declare": {
    "id": "open/pay/add-declare",
    "title": "2.1 海关申报接口",
    "sidebar_label": "2.1 海关申报接口",
    "source": "open/pay/add-declare.md",
    "permalink": "open/pay/add-declare.html",
    "localized_id": "open/pay/add-declare",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 22,
    "next_id": "open/pay/modify-declare",
    "next": "open/pay/modify-declare",
    "previous_id": "open/pay/query-refund",
    "previous": "open/pay/query-refund",
    "previous_title": "1.5 接入方查询退款订单",
    "next_title": "2.2 海关申报修改接口"
  },
  "open/pay/cancel-pay": {
    "id": "open/pay/cancel-pay",
    "title": "1.3 接入方执行支付订单取消",
    "sidebar_label": "1.3 接入方执行支付订单取消",
    "source": "open/pay/cancel-pay.md",
    "permalink": "open/pay/cancel-pay.html",
    "localized_id": "open/pay/cancel-pay",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 19,
    "next_id": "open/pay/request-refund",
    "next": "open/pay/request-refund",
    "previous_id": "open/pay/query-pay",
    "previous": "open/pay/query-pay",
    "previous_title": "1.2 接入方查询支付订单",
    "next_title": "1.4 接入方发起退款"
  },
  "open/pay/modify-declare": {
    "id": "open/pay/modify-declare",
    "title": "2.2 海关申报修改接口",
    "sidebar_label": "2.2 海关申报修改接口",
    "source": "open/pay/modify-declare.md",
    "permalink": "open/pay/modify-declare.html",
    "localized_id": "open/pay/modify-declare",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 23,
    "next_id": "open/pay/readd-declare",
    "next": "open/pay/readd-declare",
    "previous_id": "open/pay/add-declare",
    "previous": "open/pay/add-declare",
    "previous_title": "2.1 海关申报接口",
    "next_title": "2.3 海关申报重推接口"
  },
  "open/pay/pay-params": {
    "id": "open/pay/pay-params",
    "title": "1.1 payParams参数列表",
    "sidebar_label": "1.1 payParams参数列表",
    "source": "open/pay/pay-params.md",
    "permalink": "open/pay/pay-params.html",
    "localized_id": "open/pay/pay-params",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 17,
    "next_id": "open/pay/query-pay",
    "next": "open/pay/query-pay",
    "previous_id": "open/share",
    "previous": "open/share",
    "previous_title": "转发",
    "next_title": "1.2 接入方查询支付订单"
  },
  "open/pay/query-declare": {
    "id": "open/pay/query-declare",
    "title": "2.4 海关申报查询接口",
    "sidebar_label": "2.4 海关申报查询接口",
    "source": "open/pay/query-declare.md",
    "permalink": "open/pay/query-declare.html",
    "localized_id": "open/pay/query-declare",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 25,
    "next_id": "open/material/material-upload",
    "next": "open/material/material-upload",
    "previous_id": "open/pay/readd-declare",
    "previous": "open/pay/readd-declare",
    "previous_title": "2.3 海关申报重推接口",
    "next_title": "上传素材到素材库"
  },
  "open/pay/query-pay": {
    "id": "open/pay/query-pay",
    "title": "1.2 接入方查询支付订单",
    "sidebar_label": "1.2 接入方查询支付订单",
    "source": "open/pay/query-pay.md",
    "permalink": "open/pay/query-pay.html",
    "localized_id": "open/pay/query-pay",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 18,
    "next_id": "open/pay/cancel-pay",
    "next": "open/pay/cancel-pay",
    "previous_id": "open/pay/pay-params",
    "previous": "open/pay/pay-params",
    "previous_title": "1.1 payParams参数列表",
    "next_title": "1.3 接入方执行支付订单取消"
  },
  "open/pay/query-refund": {
    "id": "open/pay/query-refund",
    "title": "1.5 接入方查询退款订单",
    "sidebar_label": "1.5 接入方查询退款订单",
    "source": "open/pay/query-refund.md",
    "permalink": "open/pay/query-refund.html",
    "localized_id": "open/pay/query-refund",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 21,
    "next_id": "open/pay/add-declare",
    "next": "open/pay/add-declare",
    "previous_id": "open/pay/request-refund",
    "previous": "open/pay/request-refund",
    "previous_title": "1.4 接入方发起退款",
    "next_title": "2.1 海关申报接口"
  },
  "open/pay/readd-declare": {
    "id": "open/pay/readd-declare",
    "title": "2.3 海关申报重推接口",
    "sidebar_label": "2.3 海关申报重推接口",
    "source": "open/pay/readd-declare.md",
    "permalink": "open/pay/readd-declare.html",
    "localized_id": "open/pay/readd-declare",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 24,
    "next_id": "open/pay/query-declare",
    "next": "open/pay/query-declare",
    "previous_id": "open/pay/modify-declare",
    "previous": "open/pay/modify-declare",
    "previous_title": "2.2 海关申报修改接口",
    "next_title": "2.4 海关申报查询接口"
  },
  "open/pay/request-refund": {
    "id": "open/pay/request-refund",
    "title": "1.4 接入方发起退款",
    "sidebar_label": "1.4 接入方发起退款",
    "source": "open/pay/request-refund.md",
    "permalink": "open/pay/request-refund.html",
    "localized_id": "open/pay/request-refund",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": "支付",
    "order": 20,
    "next_id": "open/pay/query-refund",
    "next": "open/pay/query-refund",
    "previous_id": "open/pay/cancel-pay",
    "previous": "open/pay/cancel-pay",
    "previous_title": "1.3 接入方执行支付订单取消",
    "next_title": "1.5 接入方查询退款订单"
  },
  "open/README": {
    "id": "open/README",
    "source": "open/README.md",
    "title": "open/README",
    "permalink": "open/README.html",
    "localized_id": "open/README",
    "language": "en"
  },
  "open/share": {
    "id": "open/share",
    "title": "转发",
    "sidebar_label": "转发",
    "source": "open/share.md",
    "permalink": "open/share.html",
    "localized_id": "open/share",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": null,
    "order": 16,
    "next_id": "open/pay/pay-params",
    "next": "open/pay/pay-params",
    "previous_id": "open/authorize",
    "previous": "open/authorize",
    "previous_title": "授权",
    "next_title": "1.1 payParams参数列表"
  },
  "open/signature": {
    "id": "open/signature",
    "title": "开放数据校验与解密",
    "sidebar_label": "开放数据校验与解密",
    "source": "open/signature.md",
    "permalink": "open/signature.html",
    "localized_id": "open/signature",
    "language": "en",
    "sidebar": "guide",
    "category": "开放能力",
    "subcategory": null,
    "order": 14,
    "next_id": "open/authorize",
    "next": "open/authorize",
    "previous_id": "open/login",
    "previous": "open/login",
    "previous_title": "小程序登录",
    "next_title": "授权"
  }
};
